export interface PricingModel{
  applicationName:string;
  phoneNumber: string;
  address: string;
  loanDate: string;
  loanOfficer:string ;
  branchOffice:string ;
  branchaddress:string ;
  branchPhone:string;
  calcDate: string;
  fsaguarantee: number;
  loantype: number;
  lienpos: number;
  loanAmnt: string;
  paymentfreq: number;
  pd: number;
  ballonyrs:number;
  locateral: number;
  feeAmnt: string;
  stockAmnt:string;
  lgd: number;
  ballon: number;
  AmorType1: string;
  AmorTerm1: number;
  loanProd1: number;
  TransferOption1:string;
  IntRate1: string;
  PayAmnt1: string;
  TotalInt1:string;
  AmorType2: string;
  AmorTerm2: number;
  loanProd2: number;
  TransferOption2: string;
  IntRate2: string;
  PayAmnt2: string;
  TotalInt2:number;
  AmorType3: string
  AmorTerm3: number;
  loanProd3: number;
  TransferOption3: string;
  IntRate3: string;
  PayAmnt3: string;
  TotalInt3:number;
  RecomRate1: string;
  RecomSpread1: string;
  Variance1: string;
  finalSpread1: string;
  RecomRate2: string;
  RecomSpread2: string;
  Variance2:string;
  finalSpread2: string;
  RecomRate3: string;
  RecomSpread3: string;
  Variance3: string;
  finalSpread3: string;
  COF1:string;
  COF2:string;
  COF3:string;
  PostPatRate1:string;
  PostPatRate2:string;
  PostPatRate3:string;
  PostPatSave1:string;
  PostPatSave2:string;
  PostPatSave3:string;
}